
(function(){
  const dict = {
    en: {
      "nav.about": "About",
      "nav.projects": "Projects",
      "nav.skills": "Skills",
      "nav.education": "Education",
      "nav.contact": "Contact",
      "hero.title": "Data Science student",
      "hero.tagline": "turning messy data into clear decisions.",
      "hero.sub": "I love wrangling data, building models, and telling stories with visuals.",
      "cta.seeProjects": "See Projects",
      "cta.downloadCV": "Download CV",
      "about.title": "About",
      "about.lead": "I’m <strong>Hafsa Khanum</strong>, a Data Science student focused on practical machine learning, clean analysis, and beautiful, honest visualization. My interests include model interpretability, ethical AI, and turning raw datasets into something people can actually use.",
      "about.body": "Right now I’m building strong fundamentals in <em>Python</em>, <em>statistics</em>, and <em>ML</em> — and documenting my learning in public. I’m actively looking for internships and collaborative projects.",
      "projects.title": "Projects",
      "filters.all": "All",
      "filters.ml": "ML",
      "filters.nlp": "NLP",
      "filters.viz": "Visualization",
      "proj1.title": "XGBoost — Cancer Prediction",
      "proj1.desc": "End-to-end pipeline: data cleaning, feature engineering, model training, and evaluation with explainability.",
      "proj2.title": "City Mobility Dashboard",
      "proj2.desc": "Interactive dashboard exploring commute patterns and bottlenecks; highlights actionable insights.",
      "proj3.title": "Mental Health in Text",
      "proj3.desc": "NLP signals for stress & mood from journaling data; careful with ethics and privacy.",
      "proj4.title": "More coming soon",
      "proj4.desc": "I’m actively building new projects. Follow my GitHub for updates.",
      "links.github": "GitHub ↗",
      "links.profile": "GitHub Profile ↗",
      "tags.ml": "ML",
      "tags.viz": "Visualization",
      "tags.nlp": "NLP",
      "skills.title": "Skills",
      "skills.lang": "Languages",
      "skills.tools": "Libraries & Tools",
      "skills.concepts": "Concepts",
      "skills.other": "Other",
      "edu.title": "Education",
      "edu.degree": "Bachelor of Science in Data Science",
      "edu.uni": "University of Engineering and Technology (UET) Peshawar",
      "edu.years": "2022–2026",
      "contact.title": "Contact",
      "contact.email": "Email",
      "cta.work": "Work with me",
      "cta.pitch": "Have an idea or dataset? I’d love to collaborate.",
      "cta.contact": "Get in touch",
      "footer.built": "Built with love & clean CSS.",
      "footer.top": "Back to top ↑",
      "footer.langs": "Languages (future): English · Urdu · Korean"
    },
    ur: {
      "nav.about": "تعریف",
      "nav.projects": "منصوبے",
      "nav.skills": "مہارتیں",
      "nav.education": "تعلیم",
      "nav.contact": "رابطہ",
      "hero.title": "ڈیٹا سائنس کی طالبہ",
      "hero.tagline": "گندا ڈیٹا واضح فیصلوں میں بدلنا۔",
      "hero.sub": "مجھے ڈیٹا کی صفائی، ماڈل بنانا اور کہانی سناتی بصریات پسند ہیں۔",
      "cta.seeProjects": "منصوبے دیکھیں",
      "cta.downloadCV": "سی وی ڈاؤن لوڈ",
      "about.title": "تعریف",
      "about.lead": "میں <strong>حفصہ خانم</strong> ہوں — عملی مشین لرننگ، صاف تجزیہ اور خوبصورت و سچی بصریات پر توجہ دینے والی ڈیٹا سائنس طالبہ۔ میری دلچسپیوں میں ماڈل کی تشریح پذیری، اخلاقی AI، اور خام ڈیٹا کو قابلِ استعمال صورت میں ڈھالنا شامل ہے۔",
      "about.body": "اس وقت میں <em>Python</em>، <em>اعداد و شمار</em> اور <em>ML</em> کی مضبوط بنیاد بنارہی ہوں اور اپنی سیکھ ہمیشہ شیئر کرتی ہوں۔ میں انٹرنشپس اور مشترکہ منصوبوں کی تلاش میں ہوں۔",
      "projects.title": "منصوبے",
      "filters.all": "سب",
      "filters.ml": "ایم ایل",
      "filters.nlp": "این ایل پی",
      "filters.viz": "بصریات",
      "proj1.title": "XGBoost — کینسر پیش گوئی",
      "proj1.desc": "ابتدا تا انتہا پائپ لائن: ڈیٹا صفائی، فیچر انجینئرنگ، ماڈل تربیت اور تشریح کے ساتھ جانچ۔",
      "proj2.title": "شہری نقل و حرکت ڈیش بورڈ",
      "proj2.desc": "آمدورفت کے رجحانات اور رکاوٹوں کی کھوج — عملی بصیرتیں نمایاں۔",
      "proj3.title": "متن میں ذہنی صحت",
      "proj3.desc": "ڈائری کے متن سے ذہنی دباؤ و مزاج کے اشارے — اخلاقیات و رازداری کا خیال۔",
      "proj4.title": "مزید جلد آرہے ہیں",
      "proj4.desc": "میں نئے پروجیکٹس پر کام کر رہی ہوں — GitHub فالو کریں۔",
      "links.github": "GitHub ↗",
      "links.profile": "GitHub پروفائل ↗",
      "tags.ml": "ایم ایل",
      "tags.viz": "بصریات",
      "tags.nlp": "این ایل پی",
      "skills.title": "مہارتیں",
      "skills.lang": "زبانیں",
      "skills.tools": "لائبریریز اور اوزار",
      "skills.concepts": "تصورات",
      "skills.other": "دیگر",
      "edu.title": "تعلیم",
      "edu.degree": "ڈیٹا سائنس میں بی ایس",
      "edu.uni": "یونیورسٹی آف انجینئرنگ اینڈ ٹیکنالوجی (UET) پشاور",
      "edu.years": "2026–2022",
      "contact.title": "رابطہ",
      "contact.email": "ای میل",
      "cta.work": "میرے ساتھ کام کریں",
      "cta.pitch": "کوئی آئیڈیا یا ڈیٹاسیٹ ہے؟ آئیے تعاون کریں۔",
      "cta.contact": "رابطہ کریں",
      "footer.built": "محبت اور صاف CSS کے ساتھ تیار۔",
      "footer.top": "اوپر جائیں ↑",
      "footer.langs": "زبانیں (آئندہ): انگریزی · اردو · کوریائی"
    },
    ko: {
      "nav.about": "소개",
      "nav.projects": "프로젝트",
      "nav.skills": "기술",
      "nav.education": "학력",
      "nav.contact": "연락처",
      "hero.title": "데이터 사이언스 학생",
      "hero.tagline": "지저분한 데이터를 명확한 결정으로 바꿉니다.",
      "hero.sub": "데이터 정리, 모델 구축, 스토리텔링 시각화를 좋아합니다.",
      "cta.seeProjects": "프로젝트 보기",
      "cta.downloadCV": "이력서 다운로드",
      "about.title": "소개",
      "about.lead": "저는 <strong>Hafsa Khanum</strong>으로, 실용적인 머신러닝, 깔끔한 분석, 그리고 정직한 시각화에 집중하는 데이터 사이언스 학생입니다. 모델 해석 가능성과 윤리적 AI, 원시 데이터를 사람들이 실제로 사용할 수 있는 형태로 바꾸는 데 관심이 있습니다.",
      "about.body": "현재 <em>Python</em>, <em>통계</em>, <em>ML</em>의 기초를 탄탄히 쌓고 있으며, 배움을 공개적으로 기록하고 있습니다. 인턴십과 협업 프로젝트를 찾고 있어요.",
      "projects.title": "프로젝트",
      "filters.all": "전체",
      "filters.ml": "ML",
      "filters.nlp": "NLP",
      "filters.viz": "시각화",
      "proj1.title": "XGBoost — 암 예측",
      "proj1.desc": "데이터 정제, 특징 공학, 모델 학습, 해석 포함 평가까지의 파이프라인.",
      "proj2.title": "도시 이동성 대시보드",
      "proj2.desc": "출퇴근 패턴과 병목구간을 탐색하는 인터랙티브 대시보드로 실용 인사이트 제공.",
      "proj3.title": "텍스트 속 멘탈 헬스",
      "proj3.desc": "일기 데이터에서 스트레스와 기분 신호를 탐지하는 NLP — 윤리와 프라이버시를 신중히 고려.",
      "proj4.title": "곧 더 추가됩니다",
      "proj4.desc": "새 프로젝트를 열심히 만들고 있어요. GitHub를 팔로우해 주세요.",
      "links.github": "GitHub ↗",
      "links.profile": "GitHub 프로필 ↗",
      "tags.ml": "ML",
      "tags.viz": "시각화",
      "tags.nlp": "NLP",
      "skills.title": "기술",
      "skills.lang": "언어",
      "skills.tools": "라이브러리 & 도구",
      "skills.concepts": "개념",
      "skills.other": "기타",
      "edu.title": "학력",
      "edu.degree": "데이터 사이언스 학사",
      "edu.uni": "UET 페샤와르 공과대학교",
      "edu.years": "2022–2026",
      "contact.title": "연락처",
      "contact.email": "이메일",
      "cta.work": "함께 일해요",
      "cta.pitch": "아이디어나 데이터셋이 있나요? 협업을 기대합니다.",
      "cta.contact": "메일 보내기",
      "footer.built": "사랑과 깔끔한 CSS로 제작.",
      "footer.top": "맨 위로 ↑",
      "footer.langs": "언어(예정): 영어 · 우르두 · 한국어"
    }
  };

  function applyLang(lang){
    const strings = dict[lang] || dict.en;
    document.querySelectorAll("[data-i18n]").forEach(el => {
      const key = el.getAttribute("data-i18n");
      const html = strings[key];
      if (html !== undefined) el.innerHTML = html;
    });
    document.documentElement.lang = lang;
    // Direction + body font swap for Urdu
    const dir = (lang === 'ur') ? 'rtl' : 'ltr';
    document.documentElement.setAttribute('dir', dir);
    localStorage.setItem("lang", lang);
  }

  const select = document.getElementById("langSelect");
  const saved = localStorage.getItem("lang") || "en";
  select.value = saved;
  applyLang(saved);
  select.addEventListener("change", e => applyLang(e.target.value));
})();